sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vlntmi/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true vlntmi/docker-reactapp npm run test
