sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vlntmi/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true vlntmi/docker-reactapp npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-reactapp'
  env: 'Dockerreactapp-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-505909269789'
  bucket_path: 'docker-reactapp'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY